# Generated by Django 3.1.5 on 2021-01-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('renderer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.JSONField()),
                ('born_at', models.DateTimeField(auto_now_add=True)),
                ('died_at', models.DateTimeField(blank=True, null=True)),
                ('fitness', models.FloatField(default=0.5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtargets.project')),
            ],
        ),
    ]
