# Generated by Django 3.1.5 on 2021-01-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtargets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='genotype',
            name='pde',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genotype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population', to='mtargets.project'),
        ),
    ]
