# Generated by Django 3.1.5 on 2021-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtargets', '0002_auto_20210123_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genotype',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='generations',
            field=models.IntegerField(default=0),
        ),
    ]
