# Generated by Django 3.1.5 on 2021-01-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtargets', '0004_auto_20210125_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotype',
            name='shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
