# Generated by Django 3.1.5 on 2021-05-23 06:47

from django.db import migrations


def update_renderer_name(apps, schema_editor):
    Project = apps.get_model('mtargets', 'Project')
    query = Project.objects.all()
    query.update(renderer='stripes')


class Migration(migrations.Migration):

    dependencies = [
        ('mtargets', '0007_auto_20210128_0708'),
    ]

    operations = [
        migrations.RunPython(update_renderer_name, migrations.RunPython.noop)
    ]
